import type { ArtStyle } from "./types";

export const APP_NAME = "Storybook Gen Illustration";
export const APP_TAGLINE = "An illustrated-novel production studio";

export const HORDE_CLIENT_AGENT =
  "StorybookGenIllustration:1.0:github.com/Spacepocohontas/storybook-gen-illustration";

export const DEFAULT_NEGATIVE =
  "text, watermark, signature, extra fingers, distorted hands, extra limbs, blurry face, mutated anatomy, cropped head, changing established character design";

export const STYLE_PRESETS: ArtStyle[] = [
  {
    presetId: "storybook",
    name: "Storybook illustration",
    description: "Warm narrative pictures with readable characters and gentle atmosphere.",
    promptPrefix:
      "classic storybook illustration, narrative picture-book framing, painted paper texture, clear character acting",
    colorPhilosophy: "warm earth pigments, cream paper, muted jewel shadows",
    linework: "soft graphite underdrawing, painted edges",
    lighting: "storybook key light, gentle rim, readable faces",
    texture: "paper grain, gouache body color",
    era: "timeless children's illustrated novel",
    customDirection: "",
    applyScope: "book",
  },
  {
    presetId: "manga",
    name: "Manga",
    description: "Black-and-white manga language with expressive eyes and speed.",
    promptPrefix:
      "manga illustration, screentone, crisp inks, expressive eyes, dynamic panel energy",
    colorPhilosophy: "black ink on white, selective grey tones",
    linework: "confident manga ink, varied weight",
    lighting: "high-contrast manga lighting, dramatic speed lines when needed",
    texture: "screentone, paper",
    era: "contemporary manga",
    customDirection: "",
    applyScope: "book",
  },
  {
    presetId: "90s-manga",
    name: "90s Manga",
    description: "1990s manga: dense screentones, large eyes, ornate hair.",
    promptPrefix:
      "1990s manga illustration, dense screentone, ornate hair, large expressive eyes, 90s shoujo-seinen print look",
    colorPhilosophy: "monochrome print, heavy tone sheets",
    linework: "90s manga pen, decorative blacks",
    lighting: "graphic 90s print contrast",
    texture: "magazine screentone",
    era: "1990s manga magazines",
    customDirection: "",
    applyScope: "book",
  },
  {
    presetId: "90s-anime",
    name: "90s Anime",
    description: "Cel-shaded 1990s television animation with painted backgrounds.",
    promptPrefix:
      "1990s anime still, cel animation, hand-painted background, film grain, expressive eyes",
    colorPhilosophy: "cel colors over painted bg, slightly muted broadcast palette",
    linework: "thin consistent cel outlines",
    lighting: "classic anime key light, evening practicals",
    texture: "cel paint, background gouache",
    era: "1990s television anime",
    customDirection: "",
    applyScope: "book",
  },
  {
    presetId: "90s-gothic-anime",
    name: "90s Gothic Anime",
    description: "Moonlit gothic 1990s anime with jewel shadows and architecture.",
    promptPrefix:
      "1990s gothic anime, moonlit architecture, dramatic eyes, dark romantic atmosphere, cel over painted night backgrounds",
    colorPhilosophy: "muted jewel tones, moonlight, deep indigo shadows",
    linework: "fine cel line, ornate costume edges",
    lighting: "moonlight, stained-glass practicals, cinematic rims",
    texture: "cel + oil-paint backgrounds",
    era: "1990s dark fantasy anime",
    customDirection: "",
    applyScope: "book",
  },
  {
    presetId: "hand-drawn-animation",
    name: "Hand-drawn animation",
    description: "Feature-animation stills with volume and soft shading.",
    promptPrefix:
      "hand-drawn feature animation still, volume shading, clean construction, painterly bg",
    colorPhilosophy: "rich animation paint, natural color scripts",
    linework: "animation pencil cleaned to ink",
    lighting: "cinematic animation lighting",
    texture: "animation paper, bg paint",
    era: "classic feature animation",
    customDirection: "",
    applyScope: "book",
  },
  {
    presetId: "childrens-book",
    name: "Classic children's book",
    description: "Mid-century illustrated children's-book plates.",
    promptPrefix:
      "classic illustrated children's book plate, mid-century picture book, humane characters, generous margins",
    colorPhilosophy: "limited print inks, warm paper",
    linework: "pen and wash",
    lighting: "open daylight, storybook clarity",
    texture: "print paper, watercolor wash",
    era: "mid-century children's books",
    customDirection: "",
    applyScope: "book",
  },
  {
    presetId: "watercolor",
    name: "Watercolor",
    description: "Transparent watercolor with paper bloom and soft edges.",
    promptPrefix: "watercolor illustration, paper bloom, transparent washes, visible granulation",
    colorPhilosophy: "transparent pigments, reserved whites",
    linework: "light pencil or none",
    lighting: "diffused natural light",
    texture: "cold-press paper",
    era: "fine-art illustration",
    customDirection: "",
    applyScope: "book",
  },
  {
    presetId: "ink",
    name: "Ink illustration",
    description: "Dip-pen ink drawing with hatched shadow.",
    promptPrefix: "ink illustration, dip pen, cross-hatching, editorial book plate",
    colorPhilosophy: "black ink, paper cream",
    linework: "expressive pen, hatch and stipple",
    lighting: "graphic ink contrast",
    texture: "laid paper",
    era: "literary ink plates",
    customDirection: "",
    applyScope: "book",
  },
  {
    presetId: "comic",
    name: "Comic book",
    description: "American comic coloring with held blacks and balloons-ready staging.",
    promptPrefix: "comic book illustration, held blacks, punchy color holds, superhero-adjacent staging without superhero tropes unless in-story",
    colorPhilosophy: "flat comic holds, inked blacks",
    linework: "brush ink",
    lighting: "comic spotting blacks",
    texture: "newsprint / modern comic color",
    era: "modern comics",
    customDirection: "",
    applyScope: "book",
  },
  {
    presetId: "graphic-novel",
    name: "Graphic novel",
    description: "Literary graphic-novel stills, restrained and cinematic.",
    promptPrefix: "literary graphic novel illustration, cinematic panels, restrained palette, adult literary tone",
    colorPhilosophy: "limited literary palette",
    linework: "controlled ink or brush",
    lighting: "film-noir-adjacent, story-led",
    texture: "print paper",
    era: "contemporary graphic novels",
    customDirection: "",
    applyScope: "book",
  },
  {
    presetId: "dark-fantasy",
    name: "Dark fantasy",
    description: "Shadowed fantasy painting with weather and relic detail.",
    promptPrefix: "dark fantasy illustration, weathered relics, storm light, painterly gloom",
    colorPhilosophy: "desaturated earth, cold highlights",
    linework: "painterly, little outline",
    lighting: "stormbreak, firelight, moon",
    texture: "oil and grit",
    era: "dark fantasy book cover tradition",
    customDirection: "",
    applyScope: "book",
  },
  {
    presetId: "dark-fairytale",
    name: "Dark fairytale",
    description: "Folkloric dread with beauty still intact.",
    promptPrefix: "dark fairytale illustration, folkloric, beautiful and ominous, forest-edge light",
    colorPhilosophy: "berry reds, moss, bone",
    linework: "storybook ink with painted shadow",
    lighting: "twilight forest, lanterns",
    texture: "watercolor and ink",
    era: "european fairytale plates",
    customDirection: "",
    applyScope: "book",
  },
  {
    presetId: "gothic-romance",
    name: "Gothic romance",
    description: "Candlelit interiors, longing, architecture as emotion.",
    promptPrefix: "gothic romance illustration, candlelight, longing, architectural melancholy",
    colorPhilosophy: "claret, smoke, ivory",
    linework: "soft painted edges",
    lighting: "candle and moonlight",
    texture: "oil glaze",
    era: "gothic novel illustration",
    customDirection: "",
    applyScope: "book",
  },
  {
    presetId: "cinematic",
    name: "Cinematic realism",
    description: "Film stills with anamorphic light and grounded costume.",
    promptPrefix: "cinematic realist illustration, film still, anamorphic lighting, grounded costume and set",
    colorPhilosophy: "color-scripted cinema",
    linework: "none, photographic-painterly",
    lighting: "motivated practicals, cinematic contrast",
    texture: "fine grain",
    era: "contemporary cinema",
    customDirection: "",
    applyScope: "book",
  },
  {
    presetId: "concept-art",
    name: "Concept art",
    description: "Production design frames with readable silhouette.",
    promptPrefix: "film concept art, production design, readable silhouette, environment storytelling",
    colorPhilosophy: "value-first, limited accents",
    linework: "sketch under paint",
    lighting: "design lighting, shape clarity",
    texture: "digital paint",
    era: "studio concept art",
    customDirection: "",
    applyScope: "book",
  },
  {
    presetId: "painted-fantasy",
    name: "Painted fantasy",
    description: "Oil-fantasy book illustration, luminous and detailed.",
    promptPrefix: "painted fantasy book illustration, oil painting, luminous detail, literary fantasy",
    colorPhilosophy: "luminous oils, jewel shadow",
    linework: "painted form",
    lighting: "hero light, atmospheric perspective",
    texture: "oil canvas",
    era: "fantasy novel illustration",
    customDirection: "",
    applyScope: "book",
  },
  {
    presetId: "cel",
    name: "Cel animation",
    description: "Hard cel shapes over painted bg, television clarity.",
    promptPrefix: "cel animation still, hard color shapes, painted background, tv animation clarity",
    colorPhilosophy: "cel palette",
    linework: "even cel trace",
    lighting: "simple cel shade + bg light",
    texture: "acetate over bg paint",
    era: "hand-painted cel era",
    customDirection: "",
    applyScope: "book",
  },
  {
    presetId: "vintage",
    name: "Vintage illustration",
    description: "Letterpress-era book plates and limited inks.",
    promptPrefix: "vintage book illustration, letterpress-era plate, limited inks, antique paper",
    colorPhilosophy: "limited antique inks",
    linework: "engraving or pen",
    lighting: "plate contrast",
    texture: "antique paper",
    era: "late 19th / early 20th century",
    customDirection: "",
    applyScope: "book",
  },
  {
    presetId: "pencil",
    name: "Pencil sketch",
    description: "Graphite construction with observational care.",
    promptPrefix: "graphite pencil sketch, observational, construction lines faintly present, book study",
    colorPhilosophy: "graphite greys",
    linework: "pencil, varied pressure",
    lighting: "modeled graphite",
    texture: "drawing paper",
    era: "studio sketchbook",
    customDirection: "",
    applyScope: "book",
  },
  {
    presetId: "charcoal",
    name: "Charcoal",
    description: "Velvety charcoal with mass and atmosphere.",
    promptPrefix: "charcoal drawing, velvety blacks, atmospheric mass, figure and place",
    colorPhilosophy: "charcoal black to paper",
    linework: "vine and compressed charcoal",
    lighting: "broad tonal light",
    texture: "toothed paper",
    era: "atelier drawing",
    customDirection: "",
    applyScope: "book",
  },
  {
    presetId: "oil",
    name: "Oil painting",
    description: "Full oil-painting literary plates.",
    promptPrefix: "oil painting illustration, glazed color, literary subject, museum lighting",
    colorPhilosophy: "oil pigments, warm grounds",
    linework: "painted",
    lighting: "north-light or dramatic chiaroscuro as scene requires",
    texture: "canvas weave",
    era: "easel painting",
    customDirection: "",
    applyScope: "book",
  },
  {
    presetId: "mixed",
    name: "Mixed media",
    description: "Collage, ink, paint, and paper together.",
    promptPrefix: "mixed media illustration, collage paper, ink, paint, tactile layers",
    colorPhilosophy: "layered found-color",
    linework: "mixed, torn edges",
    lighting: "physical paper light",
    texture: "collage, pastel, ink",
    era: "contemporary illustration",
    customDirection: "",
    applyScope: "book",
  },
  {
    presetId: "custom",
    name: "Custom style",
    description: "Describe the visual language. Story facts still cannot change.",
    promptPrefix: "",
    colorPhilosophy: "as directed",
    linework: "as directed",
    lighting: "as directed",
    texture: "as directed",
    era: "as directed",
    customDirection: "",
    applyScope: "book",
  },
];

export function defaultStyle(): ArtStyle {
  return { ...STYLE_PRESETS[0]! };
}

export const ASPECT_SIZE: Record<
  "portrait" | "landscape" | "square" | "wide",
  { w: number; h: number; label: string }
> = {
  portrait: { w: 512, h: 768, label: "Portrait 2:3" },
  landscape: { w: 768, h: 512, label: "Landscape 3:2" },
  square: { w: 640, h: 640, label: "Square" },
  wide: { w: 832, h: 512, label: "Wide 16:10" },
};
